[Com]
    receive_cmds_ip = "192.168.132.212"           # "192.168.132.212"
    receive_cmds_port = 5100                # 5100
    send_reports_ip = "192.168.132.60"           # "192.168.132.60"
    send_reports_port = 5101                # 5101
    send_from_port = 5100
    
[Grabber]
    enable_messages_interface = true
    send_status = true
    print_messages = false

[Cams]
    active_camera = "camera1"

    [Cams.0]
        ip = "192.168.132.210" # Artificial / 192.168.132.210
        enable_gst = true
        gst_destination_ip = "192.168.132.60"        # "192.168.132.60"
        gst_destination_port = 50010             # 5000
        save_frames = false
        recordings_dir = "recordings_first"
        send_frames_gst = true
        show_frames_gst = true
    
    [Cams.1]
        ip = "192.168.132.211" # Artificial / 192.168.132.211
        enable_gst = true
        gst_destination_ip = "192.168.132.60"        # "192.168.132.60"
        gst_destination_port = 50020             # 5001
        save_frames = false
        recordings_dir = "recordings_second"
        send_frames_gst = true
        show_frames_gst = true

["Artificial"]
    pixel_format = "PIXEL_FORMAT_BAYER_GR_8"  # PIXEL_FORMAT_RGB_8_PACKED # PIXEL_FORMAT_YUV_422_PACKED # PIXEL_FORMAT_YUV_422_YUYV_PACKED
    offset_x = 320  # 0
    offset_y = 240  # 0
    width    = 640  # 1280
    height   = 480  # 1024
    scale_x  = 1
    scale_y  = 1
    grab_fps = 20
    send_fps = 20

["mvBlueCOUGAR-X102eC"]
    pixel_format = "PIXEL_FORMAT_BAYER_GR_8"  # PIXEL_FORMAT_RGB_8_PACKED # PIXEL_FORMAT_YUV_422_PACKED # PIXEL_FORMAT_YUV_422_YUYV_PACKED
    offset_x = 320  # 0
    offset_y = 240  # 0
    width    = 640  # 1280
    height   = 480  # 1024
    scale_x  = 1
    scale_y  = 1
    grab_fps = 20
    send_fps = 20

["PT1000-CL4"]
    pixel_format = "PIXEL_FORMAT_MONO_8"
    offset_x = 0
    offset_y = 0
    width    = 640
    height   = 480
    scale_x  = 1
    scale_y  = 1
    grab_fps = -1
    send_fps = 25

["Blackfly BFLY-PGE-20E4C"]
    pixel_format = "PIXEL_FORMAT_MONO_8"
    offset_x = 320
    offset_y = 240
    width    = 640
    height   = 480
    scale_x  = 1
    scale_y  = 1
    grab_fps = nan
    send_fps = 25