[Cams]
    video_enabled    = true
    messages_enabled = true
    send_status      = true
    print_messages   = false
    active_camera    = "camera1"

    [Cams.0] # flir
        #cam_ip = "192.168.132.215" # Artificial / 192.168.132.210
        cam_ip = "169.227.1.1"
        enable_gst = true
        gst_destination_ip = "192.168.132.163"       # "192.168.132.163" # "192.168.132.60"
        gst_destination_port = 50010
        
        receive_cmds_ip = "192.168.132.212"          # "192.168.132.212"
        receive_cmds_port = 5011
        send_reports_ip = "192.168.132.60"           # "192.168.132.60"
        send_reports_port = 5010
        send_from_port = 5011
        
        save_frames = false
        recordings_dir = "recordings_first"
        send_frames_gst = true
        show_frames_gst = false
    
    [Cams.1] # voxi
        #cam_ip = "192.168.132.211" # Artificial / 192.168.132.211
        cam_ip = "220.20.1.1"
        enable_gst = true
        gst_destination_ip = "192.168.132.163"       # "192.168.132.163" # "192.168.132.60"
        gst_destination_port = 50020

        receive_cmds_ip = "192.168.132.212"          # "192.168.132.212"
        receive_cmds_port = 5021
        send_reports_ip = "192.168.132.60"           # "192.168.132.60"
        send_reports_port = 5020
        send_from_port = 5021
        
        save_frames = false
        recordings_dir = "recordings_second"
        send_frames_gst = true
        show_frames_gst = false

["Artificial"]
    pixel_format = "PIXEL_FORMAT_BAYER_GR_8"  # PIXEL_FORMAT_RGB_8_PACKED # PIXEL_FORMAT_YUV_422_PACKED # PIXEL_FORMAT_YUV_422_YUYV_PACKED
    offset_x = 320  # 0
    offset_y = 240  # 0
    width    = 640  # 1280
    height   = 480  # 1024
    binning = -1
    scale_x  = 1
    scale_y  = 1
    grab_fps = 25
    send_fps = 20

["mvBlueCOUGAR-X102eC"]
    pixel_format = "PIXEL_FORMAT_BAYER_GR_8"  # PIXEL_FORMAT_RGB_8_PACKED # PIXEL_FORMAT_YUV_422_PACKED # PIXEL_FORMAT_YUV_422_YUYV_PACKED
    offset_x = 320  # 0
    offset_y = 240  # 0
    width    = 640  # 1280
    height   = 480  # 1024
    binning = -1
    scale_x  = 1
    scale_y  = 1
    grab_fps = 20
    send_fps = 20

["PT1000-CL4"]
    pixel_format = "PIXEL_FORMAT_MONO_8"
    offset_x = 0
    offset_y = 0
    width    = 640
    height   = 480
    binning = -1
    scale_x  = 1
    scale_y  = 1
    grab_fps = -1
    send_fps = 25

["Blackfly BFLY-PGE-20E4C"]
    pixel_format = "PIXEL_FORMAT_MONO_8"
    offset_x = 80
    offset_y = 60
    width    = 640
    height   = 480
    binning = 2
    scale_x  = 1
    scale_y  = 1
    grab_fps = 25
    send_fps = 25
